%%% -----------------------------------------------------
%%% Setting up 

coarseFreqComp = comm.CoarseFrequencyCompensator( ...
    Modulation="qpsk", ...
    SampleRate=sampleRate, ...
    FrequencyResolution=100);

% symbolSync = comm.SymbolSynchronizer(...
%     'SamplesPerSymbol',sps, ...
%     'NormalizedLoopBandwidth',0.01, ...
%     'DampingFactor',0.9, ...
%     'TimingErrorDetector','Gardner (non-data-aided)');
% 
% fineFreqComp = comm.CarrierSynchronizer( ...
%     'DampingFactor',0.7, ...
%     'NormalizedLoopBandwidth',0.01, ...
%     'SamplesPerSymbol',1, ...
%     'Modulation','QPSK');

symbolSync = comm.SymbolSynchronizer(...
    'SamplesPerSymbol',sps, ...
    'NormalizedLoopBandwidth',0.01, ...
    'DampingFactor',1, ...
    'TimingErrorDetector','Gardner (non-data-aided)');

fineFreqComp = comm.CarrierSynchronizer( ...
    'DampingFactor',1, ...
    'NormalizedLoopBandwidth',0.01, ...
    'SamplesPerSymbol',1, ...
    'Modulation','QPSK');