function [rxMessage, rxHeader] = ...
    frameSyncOverflow(rxSignal, frameStart, isOverflow, overflowSize, ...
                      preamble, frameSize, header)

    if (~isOverflow)
        rxMessage = ...
            rxSignal(frameStart+length(preamble)+length(header):...
                     frameStart+length(preamble)+length(header)+frameSize-1);
    
        rxHeader = rxSignal(frameStart+length(preamble):...
                            frameStart+length(preamble)+length(header)-1);
    else
        disp("Something overflow");
    end
end