function SignalThroughChannel = SimulationChannel(txSignal, sampleRate, ...
    SNR, pOffset, fOffset)

    % Gaussian channel w/ phase and frequency offset
    SignalThroughChannel = awgn(txSignal, SNR);
    pfo = comm.PhaseFrequencyOffset("PhaseOffset", pOffset, "FrequencyOffset", fOffset, ...
        "SampleRate", sampleRate);
    SignalThroughChannel = step(pfo, SignalThroughChannel);

    % Rician Channel
    % ricianchan = comm.RicianChannel( ...
    %     'SampleRate',sampleRate, ...
    %     'PathDelays',[0.0 0.5 1.2]*1e-6, ...
    %     'AveragePathGains',[0.1 0.5 0.2], ...
    %     'KFactor',2.8, ...
    %     'DirectPathDopplerShift',5.0, ...
    %     'DirectPathInitialPhase',0.5, ...
    %     'MaximumDopplerShift',50, ...
    %     'DopplerSpectrum',doppler('Bell', 8), ...
    %     'RandomStream','mt19937ar with seed', ...
    %     'Seed',73, ...
    %     'PathGainsOutputPort',true);
    % SignalThroughChannel = ricianchan(txSignal);
end