run("setupParameters.m");

% Set up the receiver
% Use the default value of 0 for FrequencyCorrection, which corresponds to 
% the factory-calibrated condition
rx = sdrrx('Pluto', 'RadioID', 'usb:0', 'CenterFrequency', centerFreq, ...
           'BasebandSampleRate', sampleRate, 'SamplesPerFrame', numSamples, ...
           'OutputDataType', 'double', 'ShowAdvancedProperties', true);
       
% Use the info method to show the actual values of various hardware-related properties
rxRadioInfo = info(rx)

% Setting up objects for correction
coarseCompensator = comm.CoarseFrequencyCompensator(...
    Modulation = modulationType, ...
    SampleRate = sampleRate, ...
    FrequencyResolution = 1);

fineSynchronizer = comm.CarrierSynchronizer(...
    "DampingFactor", 0.4, ...
    "NormalizedLoopBandwidth", 0.001, ...
    "SamplesPerSymbol", 1, ...
    "Modulation", modulationType);

phaseSync = comm.CarrierSynchronizer('Modulation', modulationType, ...
    'SamplesPerSymbol', sps);
