rxSignal = rx();
% scatterplot(rxSignal);

% Matched Filtering
rxFiltered = upfirdn(rxSignal, rrcFilter, 1, 1);
rxFiltered = rxFiltered(sps*span+1:end-(sps*span-1));
% scatterplot(rxFiltered);

% CFC
coarseFreqComp = comm.CoarseFrequencyCompensator( ...
    Modulation="qpsk", ...
    SampleRate=sampleRate, ...
    FrequencyResolution=100);
rxSignalCoarse = coarseFreqComp(rxFiltered);
scatterplot(rxSignalCoarse);

% Timing Synchronization
symbolSync = comm.SymbolSynchronizer(...
    'SamplesPerSymbol',sps, ...
    'NormalizedLoopBandwidth',0.01, ...
    'DampingFactor',0.7, ...
    'TimingErrorDetector','Gardner (non-data-aided)');
rxTimingSync = symbolSync(rxSignalCoarse);
scatterplot(rxTimingSync);

fineFreqComp = comm.CarrierSynchronizer( ...
    'SamplesPerSymbol',sps, ...
    'NormalizedLoopBandwidth',0.01, ...
    'DampingFactor',0.7, ...
    'Modulation','QPSK');
rxSignalFine = fineFreqComp(rxTimingSync);
scatterplot(rxSignalFine);

