function rxFreqSync = FrequencyCorrection(rxFiltered, sampleRate, sps)
    coarseCompensator = comm.CoarseFrequencyCompensator(...
        Modulation = "qam", ...
        SampleRate = sampleRate, ...
        FrequencyResolution = 1);
    [rxCoarseComp, ~] = coarseCompensator(rxFiltered);
    
    fineSynchronizer = comm.CarrierSynchronizer(...
        "DampingFactor", 0.7, ...
        "NormalizedLoopBandwidth", 0.005, ...
        "SamplesPerSymbol", sps, ...
        "Modulation", "QAM");
    rxFineSync = fineSynchronizer(rxCoarseComp);

    rxFreqSync = rxFineSync;q
end