%%% -----------------------------------------------------
%%% Setting up 

% coarseFreqComp = comm.CoarseFrequencyCompensator( ...
%     Modulation="qpsk", ...
%     SampleRate=sampleRate, ...
%     FrequencyResolution=100);
% 
% symbolSync = comm.SymbolSynchronizer(...
%     'SamplesPerSymbol',sps, ...
%     'NormalizedLoopBandwidth',0.01, ...
%     'DampingFactor',1, ...
%     'TimingErrorDetector','Gardner (non-data-aided)');
% 
% fineFreqComp = comm.CarrierSynchronizer( ...
%     'SamplesPerSymbol',1, ...
%     'NormalizedLoopBandwidth',0.01, ...
%     'DampingFactor',1, ...
%     'Modulation','QPSK');


% For testing:
coarseFreqComp = comm.CoarseFrequencyCompensator( ...
    Modulation="qpsk", ...
    SampleRate=sampleRate/sps, ...
    FrequencyResolution=100);

symbolSync = comm.SymbolSynchronizer(...
    'SamplesPerSymbol',sps, ...
    'NormalizedLoopBandwidth',0.01, ...
    'DampingFactor',1, ...
    'TimingErrorDetector','Gardner (non-data-aided)', ...
    'DetectorGain', 2.8);

fineFreqComp = comm.CarrierSynchronizer( ...
    'SamplesPerSymbol',1, ...
    'NormalizedLoopBandwidth',0.01, ...
    'DampingFactor',1, ...
    'Modulation','QPSK');
