%%% -----------------------------------------------------
%%% Setting up 

coarseFreqComp = comm.CoarseFrequencyCompensator( ...
    Modulation="qpsk", ...
    SampleRate=sampleRate, ...
    FrequencyResolution=1);

symbolSync = comm.SymbolSynchronizer(...
    'SamplesPerSymbol',sps, ...
    'NormalizedLoopBandwidth',0.005, ...
    'DampingFactor',1, ...
    'TimingErrorDetector','Early-Late (non-data-aided)');

fineFreqComp = comm.CarrierSynchronizer( ...
    'DampingFactor',1.3, ...
    'NormalizedLoopBandwidth',0.05, ...
    'SamplesPerSymbol',sps, ...
    'Modulation','QPSK');

eq = comm.LinearEqualizer('Algorithm','CMA', ...
    'NumTaps', 5, ...
    'StepSize',0.01);

prbdet = comm.PreambleDetector(preambleMod);