frameSize = 1000;

fileReader = dsp.AudioFileReader(...
    'Filename', "stry(1).wav", ...
    'SamplesPerFrame', frameSize);
deviceWriter = audioDeviceWriter( ...
    'SampleRate', fileReader.SampleRate);

dRC = compressor(-15, 7, ...
    'KneeWidth', 5, ...
    'SampleRate', fileReader.SampleRate);

x = fileReader();